### ISSUE TITLE
tw_thumb files pollute albums

### ISSUE THREAD

**Issue by mindhaq** [umrysh/Piwigo-Twitter-Cards#1]
With this plugin activated, my albums are polluted with new images, all having a tw_thumb filename suffix. Then, these duplicates show up in my slideshows.

Any images required for the twitter cards should not end up as regular images in the gallery.

**Comment by umrysh** [comment]
I believe this was fixed in commit 6201e4e3c1c5d7bb7f5cd5a7b85c47070f3a2a96

If this is still occurring please let me know as I am closing this issue.
